/*
  Warnings:

  - The values [CONTACT_REMOVAL] on the enum `Action` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "Action_new" AS ENUM ('CREATE', 'UPDATE', 'DELETE', 'INITATE_REGISTRATION', 'RESEND_VERIFICATION', 'LOGIN', 'RESET_PASSWORD', 'BUSINESS_ONBOARDING', 'WITHDRAWAL_ACCOUNT', 'CONTACT_INVITATION', 'MANAGE_CONTACT', 'SUBSCRIPTION_PLAN', 'SUBSCRIPTION_PLAN_PRICE', 'SUBSCRIPTION_PLAN_ROLE', 'MANAGE_COUPON', 'USE_COUPON', 'MANAGE_BILLING', 'CUSTOMER_REGISTRATION', 'SUBSCRIPTION_INITIATION', 'SUBSCRIPTION_PAYMENT', 'SUBSCRIPTION_RENEWAL_INITIATION', 'SUBSCRIPTION_UPGRADE_INITIATION', 'CUSTOM_EMAIL_NOTIFICATION', 'CUSTOM_WHATSAPP_NOTIFICATION', 'MANAGE_COURSE', 'MANAGE_COURSE_MODULE', 'MANAGE_MODULE_CONTENT', 'MANAGE_MULTIMEDIA', 'COURSE_PAYMENT_INITIATION', 'TICKET_PAYMENT_INITIATION', 'COURSE_PAYMENT_CONFIRMATION', 'TICKET_PAYMENT_CONFIRMATION', 'PRODUCT_PAYMENT_INITIATION', 'PRODUCT_PAYMENT_CONFIRMATION', 'OPERATE_CART', 'UPDATE_COURSE_PROGRESS', 'MANAGE_PRODUCT_CATEGORY', 'MANAGE_TICKET', 'SUSPEND_UNSUSPEND_BUSINESS', 'SUSPEND_UNSUSPEND_USER');
ALTER TABLE "logs" ALTER COLUMN "action" TYPE "Action_new" USING ("action"::text::"Action_new");
ALTER TYPE "Action" RENAME TO "Action_old";
ALTER TYPE "Action_new" RENAME TO "Action";
DROP TYPE "Action_old";
COMMIT;
